In [4]:
import pandas as pd

df = pd.read_csv("../../results/init_duration_results.csv")

df.head()

         function_name architecture  memory_size  init_duration_ms
0  lambda-01-x86-512mb       x86_64          512             96.58
1  lambda-02-x86-512mb       x86_64          512             73.28
2  lambda-03-x86-512mb       x86_64          512            103.95
3  lambda-04-x86-512mb       x86_64          512             68.09
4  lambda-05-x86-512mb       x86_64          512             92.78

In [5]:
df["init_duration_ms"] = pd.to_numeric(
    df["init_duration_ms"],
    errors="coerce"
)

df = df.dropna(subset=["init_duration_ms"])

In [6]:
media = df["init_duration_ms"].mean()
mediana = df["init_duration_ms"].median()
desvio_padrao = df["init_duration_ms"].std()
minimo = df["init_duration_ms"].min()
maximo = df["init_duration_ms"].max()

print(f"Média: {media:.2f} ms")
print(f"Mediana: {mediana:.2f} ms")
print(f"Desvio padrão: {desvio_padrao:.2f} ms")
print(f"Mínimo: {minimo:.2f} ms")
print(f"Máximo: {maximo:.2f} ms")

Média: 80.78 ms
Mediana: 83.20 ms
Desvio padrão: 11.33 ms
Mínimo: 43.71 ms
Máximo: 103.95 ms

In [7]:
df["init_duration_ms"].describe()

count     50.000000
mean      80.776200
std       11.326857
min       43.710000
25%       78.242500
50%       83.200000
75%       86.062500
max      103.950000
Name: init_duration_ms, dtype: float64

In [8]:
df.groupby("architecture")["init_duration_ms"].agg(
    ["count", "mean", "median", "std", "min", "max"]
)

              count     mean  median        std    min     max
architecture
arm64            25  77.3460   82.33  12.676902  43.71   93.08
x86_64           25  84.2064   83.75   8.759236  67.74  103.95

In [12]:
df.groupby(
    ["architecture", "memory_size"]
)["init_duration_ms"].agg(
    ["count", "mean", "median", "std", "min", "max"]
)

                          count     mean  median        std    min     max
architecture memory_size
arm64        512             25  77.3460   82.33  12.676902  43.71   93.08
x86_64       512             25  84.2064   83.75   8.759236  67.74  103.95